[package]
name = "hlpLib"
version = "0.0.1"
authors = ["juy13"]
edition = "2018"


[[bin]]
name = "hlpTest"
path = "rust/hlpFn.rs"

[lib]
name = "hlp_Lib"
path = "rust/hlp_Lib.rs"
crate-type = ["cdylib"]