/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef mozilla_wr_bindings_h
#define mozilla_wr_bindings_h

#pragma once

/* Generated with cbindgen:0.19.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#define VERSION 1

typedef struct ControlHex {
    int With_X         = 1;
    int WithOut_X      = 1;
    int With_Space     = 1;
    int WithOut_Space  = 1;
}ControlHex;

extern "C" int32_t add_numbers(int32_t number1, int32_t number2);

extern "C" int32_t hex2ascii(size_t hex_len,
                  unsigned char* hex_in,
                  size_t *ascii_len,
                  char* ascii_out,
                  struct ControlHex control);

#endif /* mozilla_wr_bindings_h */

/* Text to put at the end of the generated file */
