/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef mozilla_wr_bindings_h
#define mozilla_wr_bindings_h

#pragma once

/* Generated with cbindgen:0.19.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#define VERSION 1

typedef enum ControlHex {
    With_X          = 1,
    With_Space      = 2,
    WithOut_Space   = 3,
}ControlHex;

typedef enum ControlError {
    OK           = 0,
    ERRDat       = 1,
    ERRLen       = 2,
    FATErr       = 255,
}ControlError;

extern "C" int32_t add_numbers(int32_t number1, int32_t number2);


/****************************************************************************************/
/*                This function was made to conver bytes in string                      */
/*  Input:                                                                              */
/*      -- hex_len      - length of bytearray                                           */
/*      -- hex_in       - bytearray                                                     */
/*      -- ascii_len    - length of allocated memmory                                   */
/*      -- control      - type of output string                                         */
/*  Output:                                                                             */
/*      -- ascii_out    - pointer on output string                                      */
/*      -- ascii_len    - length of output string                                       */
/****************************************************************************************/

extern "C" ControlError hex2ascii(size_t hex_len,
                            unsigned char* hex_in,
                            size_t *ascii_len,
                            char* ascii_out,
                            ControlHex control);




extern "C" ControlError ascii2hex(size_t ascii_len,
                            char* ascii_in,
                            size_t *hex_len,
                            unsigned char* hex_out,
                            ControlHex control);


#endif /* mozilla_wr_bindings_h */

/* Text to put at the end of the generated file */
